name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: quitsh
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: lint
        run: just ci just lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: quitsh
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build
        run: just ci just build

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: quitsh
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: package
        run: just package-nix

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: quitsh
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: test
        run: just ci just test

      - name: coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./.output/coverage/data/coverage.txt
